version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/servers/prometheus/data:/data
    ports:
      - "9090:9090"
